#!/usr/bin/env python
"""
Signals CloudFormation SUCCESS if within a certain time the ELB thinks the instance is healthy, FAILURE if not.

Usage:
    cfn-signal-elb-healthcheck [options] ELB_NAME ASG_LOGICAL_RESOURCE_NAME STACK_NAME

Options:
     --healthy-timeout=SECONDS  Time to wait for this instance to become healthy [default: 120]
     --instance-id=STRING       Instance id of the instance to signal, uses instance metadata by default
     --region=STRING            Region of the AWS regions to connect to, uses instance metadata by default
"""

import sys
import logging

from cseh.HealthChecker import HealthChecker
from docopt import docopt


logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', datefmt='%Y-%m-%dT%H:%M:%S', level=logging.INFO)
logger = logging.getLogger(__name__)

arguments = docopt(__doc__)

elb_name = arguments["ELB_NAME"]
stack_name = arguments["STACK_NAME"]
asg_logical_resource_id = arguments["ASG_LOGICAL_RESOURCE_NAME"]
timeout = int(arguments["--healthy-timeout"])
instance_id = arguments["--instance-id"]
region = arguments["--region"]

try:
    HealthChecker(asg_logical_resource_id, stack_name, region, instance_id).wait_for_elb_healthcheck(elb_name, timeout)
except Exception as e:
    logger.exception(e)
    sys.exit(1)

