#!/usr/bin/env python
"""
Usage:
    signal-elb-healthcheck ELB_NAME ASG_LOGICAL_RESOURCE_NAME STACK_NAME

Options:
"""

import sys
import logging

from cseh.Signaller import Signaller
from cseh.HealthChecker import HealthChecker
from docopt import docopt
from cseh import get_instance_id


logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', datefmt='%Y-%m-%dT%H:%M:%S', level=logging.INFO)
logger = logging.getLogger(__name__)

arguments = docopt(__doc__)

elb_name = arguments["ELB_NAME"]
stack_name = arguments["STACK_NAME"]
asg_logical_resource_id = arguments["ASG_LOGICAL_RESOURCE_NAME"]

try:
    Signaller().signal(asg_logical_resource_id,
                       stack_name,
                       get_instance_id(),
                       HealthChecker().elb_healthcheck(elb_name))
except Exception as e:
    logger.exception(e)
    sys.exit(1)

