#!/usr/bin/env python
"""
Usage:
    signal-elb-healthcheck ELB_NAME

Options:
"""

import sys
import logging

from docopt import docopt
from cseh import HealthChecker


logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', datefmt='%Y-%m-%dT%H:%M:%S', level=logging.INFO)
logger = logging.getLogger(__name__)

arguments = docopt(__doc__)

elb_name = arguments["ELB_NAME"]

try:
    HealthChecker().elb_healthcheck(elb_name)
except Exception as e:
    print "[ERROR] %s" % e
    sys.exit(1)

